# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

git:
  depth: 10
  # Handle git submodules yourself
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

language: python
script: "make test"
